version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: motaccount-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/motaccountweb-api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2304
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: motaccount-front
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: motaccount-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: motaccountweb-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2304
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

